import "dotenv/config";

import { writeFile } from "node:fs/promises";
import path from "node:path";
import { hashPassword } from "@better-auth/utils/password";
import { PrismaPg } from "@prisma/adapter-pg";
import { nanoid } from "nanoid";
import { PrismaClient } from "./generated/prisma/client";

const connectionString = process.env.DATABASE_URL;

if (!connectionString) {
  throw new Error("DATABASE_URL is required to run seed");
}

const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString }),
});

const SUPERUSER_EMAIL = process.env.SUPERUSER_EMAIL || "superuser@seed.local";
const SUPERUSER_PASSWORD = process.env.SUPERUSER_PASSWORD || process.env.SEED_PASSWORD || "test1234";
const SUPERUSER_NAME = process.env.SUPERUSER_NAME || "Superuser";

const hpCatalog = [
  { brand: "Samsung", models: ["Galaxy A12", "Galaxy A15", "Galaxy A24", "Galaxy S21", "Galaxy M14"] },
  { brand: "Xiaomi", models: ["Redmi Note 10", "Redmi Note 12", "POCO X3", "POCO M5", "Redmi 12"] },
  { brand: "Apple", models: ["iPhone 11", "iPhone 12", "iPhone 13", "iPhone XR", "iPhone SE"] },
  { brand: "OPPO", models: ["A15", "A16", "Reno 7", "A57", "Find X5"] },
  { brand: "vivo", models: ["Y12", "Y21", "V25", "Y27", "V29"] },
  { brand: "realme", models: ["C11", "C35", "Narzo 50", "9 Pro", "GT Neo"] },
  { brand: "Infinix", models: ["Hot 10", "Hot 12", "Note 30", "Zero 5G", "Smart 7"] },
  { brand: "TECNO", models: ["Spark 10", "Pova 5", "Camon 20", "Pop 7", "Pova Neo"] },
  { brand: "Huawei", models: ["Nova 7", "P30", "Y9a", "Mate 20", "Nova Y70"] },
  { brand: "ASUS", models: ["Zenfone 8", "Zenfone 9", "ROG Phone 5", "ROG Phone 6", "Zenfone Max"] },
];

async function resetDatabase() {
  await prisma.$transaction(async (tx) => {
    await tx.activityLog.deleteMany();
    await tx.invoiceItem.deleteMany();
    await tx.invoice.deleteMany();
    await tx.serviceItem.deleteMany();
    await tx.warrantyClaim.deleteMany();
    await tx.service.deleteMany();
    await tx.inventoryAuditItem.deleteMany();
    await tx.inventoryAuditSession.deleteMany();
    await tx.sparepartCompatibility.deleteMany();
    await tx.sparepart.deleteMany();
    await tx.sparepartCategory.deleteMany();
    await tx.servicePricelist.deleteMany();
    await tx.subscriptionPayment.deleteMany();
    await tx.subscriptionInvoice.deleteMany();
    await tx.affiliateCommission.deleteMany();
    await tx.referral.deleteMany();
    await tx.affiliator.deleteMany();
    await tx.userToko.deleteMany();
    await tx.subscription.deleteMany();
    await tx.verification.deleteMany();
    await tx.session.deleteMany();
    await tx.account.deleteMany();
    await tx.user.deleteMany();
    await tx.tokoWhatsappSetting.deleteMany();
    await tx.tokoFeatureSetting.deleteMany();
    await tx.toko.deleteMany();
    await tx.hpCatalog.deleteMany();
    await tx.brand.deleteMany();
  }, { timeout: 120_000 });
}

async function seedHpCatalog() {
  let deviceCount = 0;

  for (const entry of hpCatalog) {
    const brand = await prisma.brand.create({
      data: { name: entry.brand },
      select: { id: true },
    });

    await prisma.hpCatalog.createMany({
      data: entry.models.map((modelName) => ({
        brandId: brand.id,
        modelName,
      })),
    });

    deviceCount += entry.models.length;
  }

  return {
    brandCount: hpCatalog.length,
    deviceCount,
  };
}

async function seedSuperuser() {
  const passwordHash = await hashPassword(SUPERUSER_PASSWORD);

  const user = await prisma.user.create({
    data: {
      id: nanoid(),
      name: SUPERUSER_NAME,
      email: SUPERUSER_EMAIL,
      role: "superuser",
      emailVerified: true,
    },
    select: { id: true, email: true, name: true, role: true },
  });

  await prisma.account.create({
    data: {
      id: nanoid(),
      accountId: user.id,
      providerId: "credential",
      userId: user.id,
      password: passwordHash,
    },
  });

  await prisma.subscription.create({
    data: {
      userId: user.id,
      plan: "enterprise",
    },
  });

  return user;
}

async function writeLoginMarkdown(user: Awaited<ReturnType<typeof seedSuperuser>>) {
  const outputPath = path.join(process.cwd(), "dev-doc", "dev-seed-logins.md");
  const lines = [
    "# Dev Seed Logins",
    "",
    "Generated by `prisma/seed.ts`.",
    "",
    "| Name | Email | Role | Password |",
    "| --- | --- | --- | --- |",
    `| ${user.name} | ${user.email} | ${user.role} | ${SUPERUSER_PASSWORD} |`,
    "",
  ];

  await writeFile(outputPath, `${lines.join("\n")}`, "utf8");

  return outputPath;
}

async function main() {
  console.log("Starting minimal seed");
  await resetDatabase();

  const catalog = await seedHpCatalog();
  const user = await seedSuperuser();
  const loginDocPath = await writeLoginMarkdown(user);

  console.log("Seed complete");
  console.log(`Brands: ${catalog.brandCount}`);
  console.log(`Devices: ${catalog.deviceCount}`);
  console.log(`Superuser: ${user.email}`);
  console.log(`Login doc: ${loginDocPath}`);
}

main()
  .catch((error) => {
    console.error("Seed failed", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
